version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    allow:
      - dependency-type: all
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 3
    labels: []
    commit-message:
      prefix: chore(deps)
    groups:
      minor-and-patch:
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 3
    labels: []
    commit-message:
      prefix: ci
    groups:
      minor-and-patch:
        update-types: [minor, patch]
